### ISSUE TITLE
Unable to download the data from Google Drive

### ISSUE THREAD

**Issue by ghost** [zjunlp/MKG_Analogy#4]
Hi,

Thanks for this work! I was trying to download the data from Google Drive using the link provided,
and It seems to be downloading it fine till the end, but after it has finished it says "Failed - Forbidden". 
Any idea why is it?

**Comment by flow3rdown** [comment]
Thanks for your attention!

This error can be caused by a variety of reasons, and  you can refer to [How to Fix The “Failed-Forbidden” Error on Google Drive](https://cleandrive.app/failed-forbidden-error-google/). If it doesn't work, you can also try downloading it through [Baidu Pan(TeraBox) (code:7hoc)](https://pan.baidu.com/s/1WZvpnTe8m0m-976xRrH90g). Good luck.
